### ISSUE TITLE
"Not enough free memory" error with TI-84+CE 

### ISSUE THREAD

**Issue by commandblockguy** [Timendus/ticalc-usb#14]
When trying to send a file to a TI-84+CE, it always fails due to a lack of memory, regardless of the actual free memory on the calculator.

This seems to be because DUSB_PID_FREE_RAM always returns 0 on the CE - I'm not sure if there's actually a way to get the quantity of free RAM on the CE.

I'm not sure what the best solution to this would be - I guess it could just try to send the file without checking RAM capacity if the device is an ez80 calc.

**Comment by Timendus** [comment]
@commandblockguy I have deployed both fixes. Can you check if this has solved your issues? Then we can move on to the next problem, that some files don't send, in a new issue :)
