### ISSUE TITLE
Calculator support request

### ISSUE THREAD

**Issue by fhwolff** [Timendus/ticalc-usb#54]
## Device information

{
  "deviceClass": 0,
  "deviceProtocol": 0,
  "deviceSubclass": 0,
  "deviceVersionMajor": 2,
  "deviceVersionMinor": 0,
  "deviceVersionSubminor": 1,
  "manufacturerName": "Texas Instruments Incorporated",
  "productId": 57378,
  "productName": "TI-Nspire(tm) CX II Handheld",
  "serialNumber": null,
  "usbVersionMajor": 2,
  "usbVersionMinor": 0,
  "usbVersionSubminor": 0,
  "vendorId": 1105
}

## Additional information

Calculator name as written on the device: TI-Nspire CX II

## Please note

We do not promise to support any calculators, even if there are a lot of requests for them. We're just hobbyists with limited time available. There may be technical reasons why one device is easier to support than another. We may not have access to the device and not be able to test it. So please don't be offended if your request goes unanswered.

**Comment by adriweb** [comment]
You should use N-Link for the Nspire: https://lights0123.com/n-link/
