### ISSUE TITLE
Calculator support request

### ISSUE THREAD

**Issue by Mazedotexe** [Timendus/ticalc-usb#58]
## Device information

{
  "deviceClass": 0,
  "deviceProtocol": 0,
  "deviceSubclass": 0,
  "deviceVersionMajor": 2,
  "deviceVersionMinor": 0,
  "deviceVersionSubminor": 1,
  "manufacturerName": "Texas Instruments Incorporated",
  "productId": 57378,
  "productName": "TI-Nspire(tm) CX II Handheld",
  "serialNumber": null,
  "usbVersionMajor": 2,
  "usbVersionMinor": 0,
  "usbVersionSubminor": 0,
  "vendorId": 1105
}

## Additional information

Please provide this extra information so we can better support your calculator:

Calculator name as written on the device: ti nspire cx ii
This calculator can also receive files made for these other types of calculators: probably not...?
Any other technical information that might help: this is probably the millionth request for nspire, sorry (also i remember TI has something where you can file transfer on Nspires online, but i can't remember how to find it D: )

## Please note

**Comment by adriweb** [comment]
TI-Nspire linking support is here: https://lights0123.com/n-link/
